### ISSUE TITLE
Code will execute in both situations 

### ISSUE THREAD

**Issue by zaher-aa** [GSG-G11/Have-fun#28]
`innerRenderForMovies(IMGPATH, title, average, release);` and `innerRenderForBooks(img, title, author, link); ` will execute whether the condition is true or false, so you can do it like this 

```js
if (x.volumeInfo.authors === undefined) { 
     const author = ""; 
   } else { 
     const author = x.volumeInfo.authors; 
   } 
   innerRenderForBooks(img, title, author, link); 
```

https://github.com/GSG-G11/Have-fun/blob/88aeb33c46bd22c9587d0c8f2666e1c5b8e1a80c/main/main.js#L97-L104

**Comment by RandSohail** [comment]
if we did your code the author will be not defined and will make an error => render won't work

**Comment by zaher-aa** [comment]
@RandSohail Sorry, my bad
